"""Remove field from SalesItem

Revision ID: 915e3dbc2b5f
Revises: 
Create Date: 2024-10-12 01:53:04.467167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e3dbc2b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
