"""pass

Revision ID: bde8c6e2480c
Revises: 
Create Date: 2024-10-14 12:55:14.345783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde8c6e2480c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('Cash', 'M-Pesa'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('Cash', 'M-Pesa'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
